
language: php

matrix:
  include:
    - php: 7.3
  fast_finish: true


env:
  global:
    TEST_CONFIG="phpunit.xml.dist"


before_install:
  # Enable MongoDB extension
  - echo "extension=mongodb.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini || return 0
  - echo "memory_limit=2G" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini || return 0

install:
  - travis_retry composer self-update
  - composer install

script:
  - vendor/bin/phpunit --configuration $TEST_CONFIG
  - git log $(git describe --abbrev=0 --tags)...HEAD --no-merges --pretty=format:"* [%h](http://github.com/${TRAVIS_REPO_SLUG}/commit/%H) %s (%cN)"

services:
  - mongodb

after_success:
  - travis_retry php ./vendor/bin/php-coveralls -v --config .coveralls.yml -v;
